apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc-label
  name: nginx
  namespace: infrastructure
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31333
  selector:
    app: nginx-pod-label
  sessionAffinity: None
  type: NodePort
